### ISSUE TITLE
Write verilog doesn't write declaration for power net.

### ISSUE THREAD

**Issue by smunaut** [parallaxsw/OpenSTA#32] opened 2024-05-20 10:42 UTC
This is a follow up to #27  which improved the situation in some case but doesn't handle all of them properly.

Any net that's POWER/GROUND doesn't get a `wire` declaration when writing a powered netlist.

Say you have two power pins `vdd1` and `vdd2` and in the database they connect to a single net `vdd`.
What gets written is something like :

```
assign vdd1 = vdd;
assign vdd2 = vdd;
```

without any pre-declaration of `vdd`.
Now I couldn't be 100% sure from the verilog LRM, but checking what `iverilog` accepts, the RHS of an assign must be pre-declared, so the above is not actually valid verilog.

There is a `wire vdd` that should have been written prior to those assigns.

Alternatively, it could also have been written with the LHS/RHS side swapped I think :

```
assign vdd = vdd1;
assign vdd = vdd2;
```

since the LHS can be implicitely declared and the RHS is then the pin name which is existing already.

**Comment by parallaxsw** [comment] 2024-05-20 14:32
you need to supply a testcase

**Comment by smunaut** [comment] 2024-05-20 15:41
In what format ?
DEF ? OpenRoad ODB ? Verilog ?

**Comment by parallaxsw** [comment] 2024-05-23 00:20
Obviously I would prefer verilog so openroad isn't in the way but I assume the issue is physical wire related. ODB versions are not compatible so they become unreadable so DEF is better. The smaller the better.

**Comment by smunaut** [comment] 2024-05-23 10:15
[sta.tar.gz](https://github.com/parallaxsw/OpenSTA/files/15415312/sta.tar.gz)

Here are a couple examples, one that works and the other not. The only difference being the presence of a `SPECIALNET` section. Of course here that section doesn't serve much purpose, but in the real file it's filled wiht the actual routing path for that net ...

```
read_lef -tech sky130_fd_sc_hd__nom.tlef
read_def openframe_project_wrapper.bad.def
write_verilog -include_pwr_gnd bad.v
```

```
read_lef -tech sky130_fd_sc_hd__nom.tlef
read_def openframe_project_wrapper.ok.def
write_verilog -include_pwr_gnd ok.v
```

As a side note, it seems both of these produce a wrong output if `-include_pwr_gnd` isn't specified because those assigns for the power net still get written even though the ports are not present ...

**Comment by parallaxsw** [comment] 2024-05-23 21:16
Please indicate exactly what Is "bad" about bad.v; eg, what should it look like in your opinion.

**Comment by smunaut** [comment] 2024-05-23 21:31
Ah well you can just compare the two.

The `bad` is missing the `wire vgnd;` / `wire vdpwr;` / `wire vapwr;` lines.

**Comment by parallaxsw** [comment] 2024-05-24 01:46
That is not a test case. It is a few files. Please package all of the files required to reproduce the problem including a tcl run script.

**Comment by smunaut** [comment] 2024-05-24 07:49
[sta.tar.gz](https://github.com/parallaxsw/OpenSTA/files/15429855/sta.tar.gz)

**Comment by parallaxsw** [comment] 2024-05-26 16:08
This
bool DbInstanceNetIterator::hasNext()
    if (!net->getSigType().isSupply() || !net->isSpecial()) {
introduced by 
32da6397c7 Matt Liberty      2022-03-24
prevents the power/ground nets from being visible to OpenSTA.
Restoring the iterator to its previous version fixes the problem.
I have no idea what the intent of the change to the dbNetwork iterator was.

**Comment by smunaut** [comment] 2024-05-26 17:28
@parallaxsw Thank you for looking into this.
@maliberty Ping ?

**Comment by maliberty** [comment] 2024-05-27 04:36
From the commit:
```
    This hides VDD/VSS and prevents write_verilog from including

      wire VDD;
      wire VSS;

    which confuses other tools.
```
Unfortunately I didn't say which other tools.  My guess would be formal verification or LVS.  We can try restoring it and see what happens.

**Comment by smunaut** [comment] 2024-05-27 10:26
I mean, it makes sense to not write them if not writing a powered netlist for sure.

**Comment by parallaxsw** [comment] 2024-05-27 16:11
It doesn't make any sense to change the net iterator to change write_verilog.
write_verilog shouild just omit the wire declarations if -include_pwr_gnd is not present
(as @smunaut has pointed out).

**Comment by maliberty** [comment] 2024-05-29 03:54
Fixed in https://github.com/The-OpenROAD-Project/OpenROAD/pull/5174

**Closed** 2024-05-30 16:18 UTC

**Comment by smunaut** [comment] 2024-06-02 16:52
@parallaxsw May I suggest to add the following :

```diff
diff --git a/verilog/VerilogWriter.cc b/verilog/VerilogWriter.cc
index e6037a9..1e10507 100644
--- a/verilog/VerilogWriter.cc
+++ b/verilog/VerilogWriter.cc
@@ -418,7 +418,7 @@ VerilogWriter::writeAssigns(Instance *inst)
         && (include_pwr_gnd_
             || !(network_->isPower(net) || network_->isGround(net)))
         && (network_->direction(port)->isAnyOutput()
-            || network_->direction(port)->isPowerGround())
+            || (include_pwr_gnd_ && network_->direction(port)->isPowerGround()))
         && !stringEqual(network_->name(port), network_->name(net))) {
       // Port name is different from net name.
       string port_vname = netVerilogName(network_->name(port),
```

ATM in the test case above, if you look at the `netlist_weird.nl.v` file being written you'll see it creates an invalid verilog.
Now you could argue the input database is "weird" because you have power ports connected to a net that's not declared as a power net ...  but still I think since writing the power port is gated by "include_pwr_gnd_", it makes sense to also gate it here using the same condition or you end up in this situation where you write `assigns` for a port that you didn't write and is thus non-existent.

**Comment by parallaxsw** [comment] 2024-06-03 04:16
I agree that condition should be there. Good catch.
