### ISSUE TITLE
Dead Loop in `ensureMaster(Clock* gclk)`

### ISSUE THREAD

**Issue by wuheng01** [parallaxsw/OpenSTA#141] opened 2024-12-10 07:17 UTC
When creating  generated clock  by sdc command, I encountered a problem with an infinite loop.

Below is the command of creating generate clock. ( I will give the case for reproduce later
```
create_clock [get_ports {clk1}] -name clk1 -period 10

create_generated_clock -name gclk1 -source [get_ports {clk1}] -add [get_pins {gate1/GCK}] -master_clock [get_clocks {clk1}] -divide_by 1
create_generated_clock -name gclk2 -source [get_ports {clk1}] -divide_by 1 [get_pins {gate2/GCK}]

create_generated_clock -name gclk3 -source [get_pins {gate3/CK}]  -divide_by 1 [get_pins {gate3/GCK}]
```
Since I did not set the master clock for `gclk3`,  when it attempted a forward search to find its master clock.
Then Bfs iterator touched a `CK` pin which has self loop timing arc defined  in lib file.

```
  cell (CLKGATE_X1)  {
  .....
	pin (CK) {

		direction		: input;
		related_power_pin		: "VDD";
		related_ground_pin		: "VSS";
		clock_gate_clock_pin	: true;
		capacitance		: 1.852310;
		fall_capacitance	: 1.774883;
		rise_capacitance	: 1.852310;

		timing () {

			related_pin	   : "CK";
			timing_type	   : min_pulse_width;
			fall_constraint(Pulse_width_3) {
				index_1 ("0.000932129,0.0331496,0.146240");
				values ("0.028708,0.043917,0.146386");
			}
		}
```

**Comment by wuheng01** [comment] 2024-12-10 07:18
[gen_clk.tar.gz](https://github.com/user-attachments/files/18074712/gen_clk.tar.gz)

**Comment by wuheng01** [comment] 2024-12-10 07:21
Perhaps during the BFS process, we can mark the vertices we have already visited.

**Comment by wuheng01** [comment] 2024-12-10 08:28
```
void
Genclks::ensureMaster(Clock *gclk)
{
  Clock *master_clk = gclk->masterClk();
  if (master_clk == nullptr) {
    int master_clk_count = 0;
    bool found_master = false;
    Pin *src_pin = gclk->srcPin();
    ClockSet *master_clks = sdc_->findClocks(src_pin);
    ClockSet::Iterator master_iter(master_clks);
    if (master_iter.hasNext()) {
      while (master_iter.hasNext()) {
        master_clk = master_iter.next();
        // Master source pin can actually be a clock source pin.
        if (master_clk != gclk) {
          gclk->setInferedMasterClk(master_clk);
          debugPrint(debug_, "genclk", 2, " %s master clk %s",
                     gclk->name(),
                     master_clk->name());
          found_master = true;
          master_clk_count++;
        }
      }
    }
    if (!found_master) {
      // Search backward from generated clock source pin to a clock pin.
      GenClkMasterSearchPred pred(this);
      BfsBkwdIterator iter(BfsIndex::other, &pred, this);
      VertexSet visited(graph_); // + added lines
      seedSrcPins(gclk, iter);
      while (iter.hasNext()) {
        Vertex *vertex = iter.next();
        if (visited.contains(vertex)) continue; // + added lines
        visited.insert(vertex); // + added lines
        Pin *pin = vertex->pin();
        if (sdc_->isLeafPinClock(pin)) {
          ClockSet *master_clks = sdc_->findLeafPinClocks(pin);
          if (master_clks) {
            ClockSet::Iterator master_iter(master_clks);
            if (master_iter.hasNext()) {
              master_clk = master_iter.next();
              // Master source pin can actually be a clock source pin.
              if (master_clk != gclk) {
                gclk->setInferedMasterClk(master_clk);
                debugPrint(debug_, "genclk", 2, " %s master clk %s",
                           gclk->name(),
                           master_clk->name());
                master_clk_count++;
                break;
              }
            }
          }
        }
        iter.enqueueAdjacentVertices(vertex);
      }
    }
    if (master_clk_count > 1)
      report_->warn(1061,
                    "generated clock %s pin %s is in the fanout of multiple clocks.",
                    gclk->name(),
                    network_->pathName(src_pin));
  }
}
```

**Comment by jjcherry56** [comment] 2024-12-11 19:21
The testcase does not run in OpenSTA;l it is an OpenRoad testcase.
P:lease use write_verilog to generate a testcase that does not depend on openroad.

I am pretty sure the issue can be resolved with a simple change to GenClkMasterSearchPred::searchThru that does not require a visisted set.

**Comment by wuheng01** [comment] 2024-12-12 01:34
The Verilog files have been added.
[gen_clk.tar.gz](https://github.com/user-attachments/files/18104323/gen_clk.tar.gz)

**Comment by jjcherry56** [comment] 2024-12-12 20:24
I updated the command file to use the verilog and cannot reproduce the problem in macos or ubuntu22.o4. What commit of OpenSTA are you using?

**Comment by wuheng01** [comment] 2024-12-13 10:56
Please forgive me.
My OpenSTA is too old and related issue has fixed in https://github.com/parallaxsw/OpenSTA/issues/41

**Closed** 2024-12-13 10:56 UTC
